### ISSUE TITLE
Release the current non-camlp4 version

### ISSUE THREAD

**Issue by djs55** [mirage/ocaml-qcow#20]
The ppx universe of packages needs this package, or else it isn't complete.

**Comment by djs55** [comment]
nbd.2.1.0 is a dependency: [ocaml/opam-repository#6521]

**Comment by yomimono** [comment]
`nbd 2.1.0` looks released; any chance qcow can follow?

**Comment by djs55** [comment]
OK tagged and made a PR: [ocaml/opam-repository#6721]

**Comment by yomimono** [comment]
thanks very much! :)

**Comment by hannesm** [comment]
I suspect this issue can be closed...
