### ISSUE TITLE
expose prometheus metrics

### ISSUE THREAD

**Issue by djs55** [mirage/ocaml-qcow#99]
Now that metrics have been defined for things like
- bytes read/written/discarded
- bytes of user data
- bytes erased/copied/flushed/referenced

It would be nice to be able to easily expose the metrics via the `connect` API. For example, if the metrics are scraped by prometheus and graphed by grafana:

![screenshot](https://cloud.githubusercontent.com/assets/198586/26151381/7e53db66-3afa-11e7-8608-7ba015c49910.png)

**Comment by talex5** [comment]
Why does `connect` need changing? The metrics should be exposed automatically by the prometheus library.

**Comment by djs55** [comment]
I'm looking for a nice place to put this code:
```ocaml
            let module Server = Prometheus_app.Cohttp(Cohttp_lwt_unix.Server) in
            let mode = `TCP (`Port 9090) in (* FIXME: Unix socket *)
            let callback = Server.callback in
            let server = Cohttp_lwt_unix.Server.make ~callback () in
            Lwt.async (fun () -> Cohttp_lwt_unix.Server.create ~mode server);
```
My particular use-case is a bit funny because the main application (`moby/hyperkit`) is written in C and uses this code via an OCaml function calling shim.

Maybe I should think of the OCaml shim as being more like a `main` function rather than just a means of calling `read` and `write` and stick the initialisation code there.

(Partly I wanted to create an issue somewhere with a screenshot that I can point people at since I think it looks quite nice!)

**Comment by talex5** [comment]
Yes, makes sense to keep this out of the API I think.

**Comment by samoht** [comment]
> (Partly I wanted to create an issue somewhere with a screenshot that I can point people at since I think it looks quite nice!)

This looks indeed very nice :-)
